//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace esnet_efworkshop02
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customers()
        {
            this.IssueTran = new HashSet<IssueTran>();
        }
    
        public string CustomerID { get; set; }
        public string CustomerName { get; set; }
        public string MemberRating { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<decimal> AmountSpent { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string OldPostalCode { get; set; }
        public string PostalCode { get; set; }
        public string CountryCode { get; set; }
        public string ContactTitle { get; set; }
        public string PhoneNumber { get; set; }
        public string Extension { get; set; }
        public string FaxNumber { get; set; }
        public string EmailAddress { get; set; }
        public string Notes { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual CustomerContact CustomerContact { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IssueTran> IssueTran { get; set; }
    }
}
