//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace esnet_efworkshop02
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberCategories
    {
        public string MemberCategory { get; set; }
        public string MemberCatDescription { get; set; }
    }
}
