//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace esnet_efworkshop02
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movies
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Movies()
        {
            this.IssueTran = new HashSet<IssueTran>();
            this.StockAdjustment = new HashSet<StockAdjustment>();
        }
    
        public short VideoCode { get; set; }
        public string MovieTitle { get; set; }
        public string MovieType { get; set; }
        public string Rating { get; set; }
        public Nullable<float> RentalPrice { get; set; }
        public string ProducerID { get; set; }
        public string Director { get; set; }
        public string Media { get; set; }
        public Nullable<short> TotalStock { get; set; }
        public Nullable<short> NumberRented { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IssueTran> IssueTran { get; set; }
        public virtual Producers Producers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockAdjustment> StockAdjustment { get; set; }
    }
}
